import Foundation
import CoreData


extension Budget { // The Budget class for the Budget entity was generated by XCode

    @nonobjc public class func fetchRequest() -> NSFetchRequest<Budget> {
        return NSFetchRequest<Budget>(entityName: "Budget")
    }

    @NSManaged public var limit: Int32
    @NSManaged public var budgetID: Int32
}

extension Budget : Identifiable {

}
